name: Build proot

on:
  push:
    paths:
      - 'packages/proot/**'
  workflow_dispatch:

permissions: {}

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    permissions:
      contents: read
      packages: write
    runs-on: ubuntu-26.04
    steps:
    - name: Clone repository
      uses: actions/checkout@v7

    - name: Enable zram
      uses: ./.github/actions/zram
      with:
        algorithm: zstd
        size: 16G
        priority: 100
        device_name: /dev/zram0

    - name: Free disk space
      run: ./scripts/free-space.sh

    - name: Login to GHCR
      uses: docker/login-action@v4
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Pull pre-built Docker image
      id: pull
      run: |
        if docker pull ghcr.io/${{ github.repository_owner }}/package-builder:latest; then
          echo "outcome=success" >> "$GITHUB_OUTPUT"
        else
          echo "outcome=failure" >> "$GITHUB_OUTPUT"
        fi

    - name: Set up Docker Buildx
      if: steps.pull.outputs.outcome == 'failure'
      uses: docker/setup-buildx-action@v4

    - name: Build Docker builder image
      if: steps.pull.outputs.outcome == 'failure'
      id: build-image
      uses: docker/build-push-action@v6
      with:
        context: scripts/
        load: true
        tags: ghcr.io/${{ github.repository_owner }}/package-builder:latest
        cache-from: type=gha
        cache-to: type=gha,mode=max

    - name: Push Docker image to GHCR
      if: steps.pull.outputs.outcome == 'failure'
      run: |
        for t in 1 2 3; do
          if docker push ghcr.io/${{ github.repository_owner }}/package-builder:latest; then
            break
          else
            if [ "$t" = "3" ]; then
              echo "::warning::Failed to push Docker image to GHCR after 3 attempts"
              exit 0
            fi
            sleep 20
          fi
        done

    - name: Build proot
      run: |
        ./scripts/run-docker.sh -d ./build-package.sh -I -C -a aarch64 --format pacman proot

    - name: Collect package files
      if: always()
      run: |
        mkdir -p ./artifacts
        test -d output && mv output/*.pkg.tar.xz ./artifacts/ 2>/dev/null || true
        test -d output && mv output/*.deb ./artifacts/ 2>/dev/null || true

    - name: Store package files
      if: always()
      uses: actions/upload-artifact@v6
      with:
        name: proot-aarch64-${{ github.sha }}
        path: ./artifacts/*
