name: Docker image

on:
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
    - name: Clone repository
      uses: actions/checkout@v7

    - name: Build
      run: |
        docker build --tag ghcr.io/${{ toLowerCase(github.repository_owner) }}/package-builder:latest scripts/

    - name: Login to GHCR
      uses: docker/login-action@v4
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Push to GHCR
      run: |
        for t in 1 2 3; do
          if docker push ghcr.io/${{ toLowerCase(github.repository_owner) }}/package-builder:latest; then
            break
          else
            if [ "$t" = "3" ]; then
              echo "Giving up after 3 attempts"
              exit 1
            fi
            sleep 20
          fi
        done
